### ISSUE TITLE
Preprocessing step

### ISSUE THREAD

**Issue by JaesikKim** [ssikjeong1/Deep_Recurrent_AD#2]
Hi. I'm Jaesik Kim.
I'm trying to run your code on TADPOLE dataset and replicate the experiments in the paper, but it seems the TADPOLE data I downloaded from ADNI does not fit on the implementation code.
Is there a preprocessing step? Can you share preprocessing code or processed file? (that can be directly used for your code)

Thanks!
Jaesik

**Comment by ssikjeong1** [comment]
Thanks for your question.

We referred to the following codes in our preprocessing step:

- https://github.com/noxtoby/TADPOLE

- https://github.com/ThomasYeoLab/Standalone_Nguyen2020_RNNAD/tree/master/cbig/Nguyen2020

**Comment by czp19940707** [comment]
Hi:
Could you please provide some detail about preprocessing step? The code in Nguyen2020 can generate val.pkl file, how to use that file in this repo?
Thanks!
