### ISSUE TITLE
some questions about the datasets and your code

### ISSUE THREAD

**Issue by zonghuia** [ssikjeong1/Deep_Recurrent_AD#3]
Hello, Your paper is very innovative and deeply attracted me, but I have one question about the datasets and your code.

when I wanted to run your code, I download the TADPOLE datasets, which is full of .csv files. I saw that your code use np.load() to load datasets, which is usually used for loading .npy file. I don't know how to load data. Could you tell me how to deal with the TADPOLE data after downloading it?

Thanks!

**Comment by CrushMzyyy** [comment]
Hello, I'm a Chinese student, I don't know if I can get to know each other and exchange some questions?

**Comment by ssikjeong1** [comment]
Sorry for the late reply to your questions.

As you can find the preprocessing steps in the manuscript.
* We utilize the six MRI features (ventricles, hippocampus, fusiform gyrus, middle temporal gyrus, entorhinal cortex, and whole brain) and three cognitive scores (MMSE, ADAS11, and ADAS13).

Best regards,

**Comment by southbreeze** [comment]
> Hello, Your paper is very innovative and deeply attracted me, but I have one question about the datasets and your code.
> 
> when I wanted to run your code, I download the TADPOLE datasets, which is full of .csv files. I saw that your code use np.load() to load datasets, which is usually used for loading .npy file. I don't know how to load data. Could you tell me how to deal with the TADPOLE data after downloading it?
> 
> Thanks!

Hello, have you processed the dataset yet?
